/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-24-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   04-24-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class ApexClass8 {
    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 04-24-2021 
    **/
    public ApexClass8() {
        this;
    }
}
