name: SFDX Test Run on Push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: hectorgb/sfdx-action@v1
        with:
          node-version: '14'
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      
      - uses: hectorgb/pmd-action@v1
      - name: runPmd
        run: pmd -d ./force-app/main/default/classes -R ./ruleset.xml -f text
      - name: orgList
        run: sfdx force:org:list
      - name: orgList
        run: sfdx force:org:list
      - name: installDelta
        run: npm install sfdx-git-delta@latest -g
      - name: testDelta
        run: sgd --to HEAD --from HEAD^ --repo . --output .  
      