name: SFDX Test Run on Push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: pwd
        run: pwd  
      - name: ls
        run: ls
      - name: cat ruleset.xml
        run: cat ruleset.xml
      - name: orgList
        run: sfdx force:org:list
      - name: runPmd
        run: pmd -d ./force-app/main/default/classes -R ruleset.xml -f text