name: SFDX Test Run on Push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # - name: Setup SFDX 
      #   uses: hectorgb/sfdx-action@v1
      #   with:
      #     sfdx-auth-url: ${{ secrets.AUTH_SECRET }}

      - name: Setup Git Delta
        uses: hectorgb/sfdx-git-delta-action@v2

      - name: Setup Sfdc Package Merge
        uses: hectorgb/marge-package-action@v1

      - name: Setup PMD
        uses: hectorgb/pmd-action@v1

      - name: runPmd
        run: pmd -d ./force-app/main/default/classes -R ./ruleset.xml -f text

      # - name: orgList
      #   run: sfdx force:org:list

      - name: testDelta
        run: sgd --to HEAD --from HEAD^ --repo . --output .

      - name: testPackageMerge
        run: smp -p manifest/package.xml -p package/package.xml -o merged_packed.xml
      
      - name: cat merged_packed.xml
        run: cat merged_packed.xml
      